/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view.listas;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.bean.Advogado;
import model.bean.Cliente;
import model.bean.Processo;
import model.bean.Sexo;
import model.dao.AdvogadoDAO;
import model.dao.ClienteDAO;
import model.dao.ProcessoDAO;
import model.view.TelaPricipal;

/**
 *
 * @author Pedro
 */
public class ListarProcesso extends javax.swing.JInternalFrame {
     JDesktopPane jDesktopPane1;
     Advogado adv = new Advogado();
        Cliente cli = new Cliente();
        Processo pro = new Processo();
        TelaPricipal telinha;
    /**
     * Creates new form ListarPessoaFisica
     */
    public ListarProcesso(TelaPricipal tel) {
        initComponents();
        this.telinha = tel;
       advogado.disable();
       cliente.disable();
       acao.disable();
       obs.disable();
       descri.disable();
       clint.setVisible(false);
       advo.setVisible(false);
       cod.disable();
       salv.setVisible(false);
       pesqSele.setVisible(false);
       pesqSele.disable();
        ClienteDAO cDAO = new ClienteDAO();
        for (Cliente c: cDAO.listarCliente()) {
            
            clint.addItem(c);
        }
        AdvogadoDAO aDAO = new AdvogadoDAO();
        for (Advogado a: aDAO.listarAdvogado()) {
            advo.addItem(a);
            
        } 
        
    DefaultTableModel dtm = (DefaultTableModel) tabelaProcessos.getModel();
        ProcessoDAO pDAO = new ProcessoDAO();
        for (Processo proc : pDAO.listarProcesso()) {
            dtm.addRow(new Object[]{
                proc.getCod_processo(),
                proc.getAcao(),
                proc.getDescricao()
                });
        }
        
            
       
       
    }
    public ListarProcesso() {
        initComponents();
        
       advogado.disable();
       cliente.disable();
       acao.disable();
       obs.disable();
       descri.disable();
       clint.setVisible(false);
       advo.setVisible(false);
       cod.disable();
       salv.setVisible(false);
        ClienteDAO cDAO = new ClienteDAO();
        for (Cliente c: cDAO.listarCliente()) {
            
            clint.addItem(c);
        }
        AdvogadoDAO aDAO = new AdvogadoDAO();
        for (Advogado a: aDAO.listarAdvogado()) {
            advo.addItem(a);
            
        } 
        
    DefaultTableModel dtm = (DefaultTableModel) tabelaProcessos.getModel();
        ProcessoDAO pDAO = new ProcessoDAO();
        for (Processo proc : pDAO.listarProcesso()) {
            dtm.addRow(new Object[]{
                proc.getCod_processo(),
                proc.getAcao(),
                proc.getDescricao()
                });
        }
        
            
       
       
    }
    ListarProcesso(JDesktopPane jDesktopPane1) {
        initComponents();
        this.jDesktopPane1 = jDesktopPane1;
        DefaultTableModel dtm = (DefaultTableModel) tabelaProcessos.getModel();
        ProcessoDAO pDAO = new ProcessoDAO();
        for (Processo pro : pDAO.listarProcesso()) {
            dtm.addRow(new Object[]{
                pro.getCod_processo(),
                pro.getAcao(),
                pro.getDescricao()
                });
        }
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nome1 = new javax.swing.JTextField();
        nomef1 = new javax.swing.JTextField();
        cnpj1 = new javax.swing.JFormattedTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        rua1 = new javax.swing.JTextField();
        bairro1 = new javax.swing.JTextField();
        num1 = new javax.swing.JTextField();
        estado1 = new javax.swing.JTextField();
        cep1 = new javax.swing.JTextField();
        cidade1 = new javax.swing.JTextField();
        comple1 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        tele1 = new javax.swing.JTextField();
        ddd1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProcessos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        advogado = new javax.swing.JTextField();
        cliente = new javax.swing.JTextField();
        advo = new javax.swing.JComboBox<>();
        clint = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        acao = new javax.swing.JTextField();
        descri = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        obs = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        salv = new javax.swing.JButton();
        pesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bot1 = new javax.swing.JRadioButton();
        bot2 = new javax.swing.JRadioButton();
        bot3 = new javax.swing.JRadioButton();
        bot4 = new javax.swing.JRadioButton();
        pesqTxt = new javax.swing.JTextField();
        pesqSele = new javax.swing.JComboBox<>();

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Dados do Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Georgia", 1, 18))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Informações Pessoais", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Georgia", 1, 14))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel5.setText("Nome:");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel7.setText("CNPJ:");

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel8.setText("Nome Fantasia:");

        nome1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        nome1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nome1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nome1.setPreferredSize(new java.awt.Dimension(74, 24));

        nomef1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        nomef1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nomef1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nomef1.setPreferredSize(new java.awt.Dimension(74, 24));

        cnpj1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            cnpj1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cnpj1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cnpj1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        cnpj1.setMinimumSize(new java.awt.Dimension(6, 24));
        cnpj1.setPreferredSize(new java.awt.Dimension(64, 24));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cnpj1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomef1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cnpj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomef1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Endereço", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Georgia", 1, 14))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel20.setText("Rua:");

        jLabel21.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel21.setText("Bairro:");

        jLabel22.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel22.setText("Número:");

        jLabel23.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel23.setText("CEP:");

        jLabel24.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel24.setText("Estado:");

        jLabel25.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel25.setText("Complemento:");

        jLabel26.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel26.setText("Cidade:");

        rua1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        rua1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rua1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rua1.setPreferredSize(new java.awt.Dimension(2, 24));

        bairro1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bairro1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bairro1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        bairro1.setPreferredSize(new java.awt.Dimension(2, 24));

        num1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        num1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        num1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        num1.setPreferredSize(new java.awt.Dimension(2, 24));

        estado1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        estado1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        estado1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        estado1.setPreferredSize(new java.awt.Dimension(2, 24));

        cep1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        cep1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cep1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cep1.setPreferredSize(new java.awt.Dimension(2, 24));

        cidade1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        cidade1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cidade1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cidade1.setPreferredSize(new java.awt.Dimension(2, 24));

        comple1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        comple1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comple1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        comple1.setPreferredSize(new java.awt.Dimension(2, 24));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rua1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bairro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cep1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cidade1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estado1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comple1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comple1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Contato", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Georgia", 1, 14))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel27.setText("Email:");

        jLabel28.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel28.setText("Telefone:");

        email1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        email1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        email1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        email1.setPreferredSize(new java.awt.Dimension(2, 24));

        tele1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        tele1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tele1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tele1.setPreferredSize(new java.awt.Dimension(2, 24));

        ddd1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        ddd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ddd1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ddd1.setPreferredSize(new java.awt.Dimension(2, 24));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddd1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tele1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tele1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ddd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1130, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabelaProcessos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de Registro", "Ação", "Descrição"
            }
        ));
        tabelaProcessos.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaProcessos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProcessosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProcessos);

        jButton2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton2.setText("Excluir");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Dados do Processo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Georgia", 1, 18))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Envolvidos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Georgia", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel3.setText("Advogado:");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel4.setText("Cliente:");

        advogado.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        advogado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        advogado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        advogado.setPreferredSize(new java.awt.Dimension(74, 24));

        cliente.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cliente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cliente.setPreferredSize(new java.awt.Dimension(74, 24));

        advo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        advo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Advogado" }));
        advo.setPreferredSize(new java.awt.Dimension(500, 24));

        clint.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        clint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Cliente" }));
        clint.setPreferredSize(new java.awt.Dimension(56, 24));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(advogado, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(advo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clint, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advogado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Informações do Processo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Georgia", 1, 14))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel18.setText("Ação:");

        jLabel19.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel19.setText("Descrição:");

        acao.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        acao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        acao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        acao.setPreferredSize(new java.awt.Dimension(2, 24));

        descri.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        descri.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        descri.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        descri.setPreferredSize(new java.awt.Dimension(2, 24));

        obs.setColumns(20);
        obs.setRows(5);
        obs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        obs.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(obs);

        jLabel29.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel29.setText("Obsevações:");

        jLabel30.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel30.setText("Código do Processo:");

        cod.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        cod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cod.setPreferredSize(new java.awt.Dimension(2, 24));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton4.setText("Editar");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        salv.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        salv.setText("Salvar");
        salv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        salv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvActionPerformed(evt);
            }
        });

        pesquisar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        pesquisar.setText("Pesquisar");
        pesquisar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pesquisar.setPreferredSize(new java.awt.Dimension(77, 39));
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setText("Pesquisar por:");

        bot1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(bot1);
        bot1.setText("Advogado");
        bot1.setIconTextGap(1);
        bot1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot1MouseClicked(evt);
            }
        });
        bot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot1ActionPerformed(evt);
            }
        });

        bot2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(bot2);
        bot2.setText("Cliente");
        bot2.setIconTextGap(2);
        bot2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot2MouseClicked(evt);
            }
        });

        bot3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(bot3);
        bot3.setText("Ação");
        bot3.setIconTextGap(3);
        bot3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot3MouseClicked(evt);
            }
        });

        bot4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(bot4);
        bot4.setText("Descrição");
        bot4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot4MouseClicked(evt);
            }
        });

        pesqTxt.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pesqTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Pesquisar", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Georgia", 1, 14))); // NOI18N
        pesqTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        pesqTxt.setPreferredSize(new java.awt.Dimension(74, 39));
        pesqTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqTxtActionPerformed(evt);
            }
        });

        pesqSele.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        pesqSele.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        pesqSele.setPreferredSize(new java.awt.Dimension(500, 39));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pesqTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesqSele, 0, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bot1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bot2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bot3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bot4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salv, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton3, salv});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(salv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pesqTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bot1)
                            .addComponent(bot2)
                            .addComponent(bot3)
                            .addComponent(bot4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pesqSele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButton3, salv});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int linha = tabelaProcessos.getSelectedRow();
        int codigoProcesso = (int) tabelaProcessos.getValueAt(linha, 0);
         ProcessoDAO pDAO = new ProcessoDAO();
       if(pDAO.verificaExclusao(codigoProcesso)){
           if (JOptionPane.showConfirmDialog(null, "O processo já possui uma audiência marcada, exclua a audiência primeiro para exlcuir o processo, deseja ir para audiências?")==0) {
               ListarAudiencia aud = new ListarAudiencia();
               this.telinha.jDesktopPane1.add(aud);
               aud.show();
               aud.toFront();
           }
       }else{
         Processo excluirPros = new Processo();
        excluirPros.setCod_processo(codigoProcesso);
       
        if (JOptionPane.showConfirmDialog(null, "Deseja excluir?") == 0) {
            pDAO.deletar(excluirPros);
        }
        
        
        DefaultTableModel dtm = (DefaultTableModel) tabelaProcessos.getModel();
        dtm.setNumRows(0);
        for (Processo proc : pDAO.listarProcesso()) {
                dtm.addRow(new Object[]{
                proc.getCod_processo(),
                proc.getAcao(),
                proc.getDescricao()
                });
        }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Mostra o cliente já selecionado
        boolean v= true;
        int id=1;
        int c=0;
            do{
             
            String op =String.valueOf(clint.getItemAt(id));
            
            String ente[] = new String[4];
            ente = op.split(":");
            
            
          
            if (Integer.parseInt(ente[3])==cli.getCod_cliente()){
                c=id;
                break;
                
            }
            id++;
        }while(v);
         //Mostra o advogado já selecionado
         boolean a= true;
        int ip=1;
        int f=0;
            do{
             
            String op =String.valueOf(advo.getItemAt(ip));
            
            String ente[] = new String[5];
            ente = op.split(":");
                
            
          
            if (Integer.parseInt(ente[4])==adv.getCod_adv()){
                f=ip;
                break;
                
            }
            ip++;
        }while(a);




        acao.enable();
        obs.enable();
        descri.enable();
        advogado.setVisible(false);
        cliente.setVisible(false);
        clint.setSelectedIndex(c);
        advo.setSelectedIndex(f);
        clint.setVisible(true);
       advo.setVisible(true);
       cod.enable();
       salv.setVisible(true);


        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tabelaProcessosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProcessosMouseClicked
        advogado.disable();
       cliente.disable();
       acao.disable();
       obs.disable();
       descri.disable();
       advogado.setVisible(true);
       cliente.setVisible(true); 
       clint.setVisible(false);
       advo.setVisible(false); 
       cod.disable();
       salv.setVisible(false); 
        
        
        
        int linha = tabelaProcessos.getSelectedRow();
        int codigoProcesso = (int) tabelaProcessos.getValueAt(linha, 0);
        AdvogadoDAO aDAO = new AdvogadoDAO();
        ClienteDAO cDAO = new ClienteDAO();
        
        pro.setCod_processo(codigoProcesso);
        ProcessoDAO pDAO = new ProcessoDAO();
        pDAO.buscarProcesso(pro);
        adv.setCod_adv(pro.getAdvogado().getCod_adv());
        cli.setCod_cliente(pro.getCliente().getCod_cliente());
        aDAO.buscarAdvogado(adv);
        cDAO.buscarCliente(cli);
        if (cli.getSobrenome()==null) {
            cliente.setText(cli.getNome()+" "+cli.getNome_fant());
        }else{
            cliente.setText(cli.getNome()+" "+cli.getSobrenome());
        }
        advogado.setText(adv.getNome()+" "+adv.getSobrenome());
        descri.setText(pro.getDescricao());
        obs.setText(pro.getObservacoes());
        acao.setText(pro.getAcao());
        cod.setText(pro.getCodigo());
        
        
        
        
        
        
        
    }//GEN-LAST:event_tabelaProcessosMouseClicked

    private void salvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvActionPerformed
        Processo pro = new Processo();
        Advogado adv = new Advogado();
        Cliente cli = new Cliente();
        ProcessoDAO pDAO = new ProcessoDAO();
        int linha = tabelaProcessos.getSelectedRow();
        int codigoPro = (int) tabelaProcessos.getValueAt(linha, 0);
        pro.setCod_processo(codigoPro);
        pro.setDescricao(descri.getText());
        pro.setObservacoes(obs.getText());
        pro.setAcao(acao.getText());
        pro.setCodigo(cod.getText());
        ////////Pegar opção de cliente
       String op = String.valueOf(clint.getSelectedItem());
       String ente[] = new String[4];
       ente = op.split(":");
       //////////// 
       ///////Pegar opção de advogado
       String opa = String.valueOf(advo.getSelectedItem());
       String vogado[] = new String[5];
       vogado = opa.split(":");
       ////////////
       adv.setCod_adv(Integer.parseInt(vogado[4]));
       cli.setCod_cliente(Integer.parseInt(ente[3])); 
       pro.setAdvogado(adv);
       pro.setCliente(cli);
       pDAO.editarProcesso(pro);
        
        DefaultTableModel dtm = (DefaultTableModel) tabelaProcessos.getModel();
        dtm.setNumRows(0);
        for (Processo proc : pDAO.listarProcesso()) {
            dtm.addRow(new Object[]{
                proc.getCod_processo(),
                proc.getAcao(),
                proc.getDescricao()
                });
        }
        
        
        
        
    }//GEN-LAST:event_salvActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        if (bot1.isSelected()) {
             ProcessoDAO dao = new ProcessoDAO();
             String opa = String.valueOf(pesqSele.getSelectedItem());
             String vogado[] = new String[5];
             vogado = opa.split(":");
              DefaultTableModel dtm = (DefaultTableModel) tabelaProcessos.getModel();
                 dtm.setNumRows(0);
                 for (Processo pro : dao.pesquisarProcessoPorAdvogado(vogado[4])) {
            dtm.addRow(new Object[]{
                pro.getCod_processo(),
                pro.getAcao(),
                pro.getDescricao()});
                 }

        }else if (bot2.isSelected()) {
             ProcessoDAO dao = new ProcessoDAO();
             String op = String.valueOf(pesqSele.getSelectedItem());
       String ente[] = new String[4];
       ente = op.split(":");
              DefaultTableModel dtm = (DefaultTableModel) tabelaProcessos.getModel();
                 dtm.setNumRows(0);
                 for (Processo pro : dao.pesquisarProcessoPorCliente(ente[3])) {
            dtm.addRow(new Object[]{
                pro.getCod_processo(),
                pro.getAcao(),
                pro.getDescricao()});
                 }
        }else if (bot3.isSelected()) {
            ProcessoDAO dao = new ProcessoDAO();
             
              DefaultTableModel dtm = (DefaultTableModel) tabelaProcessos.getModel();
                 dtm.setNumRows(0);
                 for (Processo pro : dao.pesquisarProcessoPorAcao(pesqTxt.getText())) {
            dtm.addRow(new Object[]{
                pro.getCod_processo(),
                pro.getAcao(),
                pro.getDescricao()});
                 }
        }else if (bot4.isSelected()) {
          ProcessoDAO dao = new ProcessoDAO();
             
              DefaultTableModel dtm = (DefaultTableModel) tabelaProcessos.getModel();
                 dtm.setNumRows(0);
                 for (Processo pro : dao.pesquisarProcessoPorDescricao(pesqTxt.getText())) {
            dtm.addRow(new Object[]{
                pro.getCod_processo(),
                pro.getAcao(),
                pro.getDescricao()});
                 }  
        }
    }//GEN-LAST:event_pesquisarActionPerformed

    private void bot1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot1MouseClicked
     pesqSele.removeAllItems();
     pesqTxt.setVisible(false);
     pesqTxt.disable();
     pesqSele.setVisible(true);
     pesqSele.enable();
     pesqSele.addItem("Selecione o Advogado");
     AdvogadoDAO aDAO = new AdvogadoDAO();
        for (Advogado a: aDAO.listarAdvogado()) {
            pesqSele.addItem(a);
            
        } 
    }//GEN-LAST:event_bot1MouseClicked

    private void bot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bot1ActionPerformed

    private void bot2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot2MouseClicked
     pesqSele.removeAllItems();
     pesqTxt.setVisible(false);
     pesqTxt.disable();
     pesqSele.setVisible(true);
     pesqSele.enable();
     pesqSele.addItem("Selecione o Cliente");
     ClienteDAO cDAO = new ClienteDAO();
        for (Cliente c: cDAO.listarCliente()) {
            
            pesqSele.addItem(c);
        }
    }//GEN-LAST:event_bot2MouseClicked

    private void bot3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot3MouseClicked
       pesqSele.setVisible(false);
       pesqSele.disable();
       pesqTxt.setVisible(true);
       pesqTxt.enable();
    }//GEN-LAST:event_bot3MouseClicked

    private void bot4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot4MouseClicked
       pesqSele.setVisible(false);
       pesqSele.disable();
       pesqTxt.setVisible(true);
       pesqTxt.enable();
    }//GEN-LAST:event_bot4MouseClicked

    private void pesqTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqTxtActionPerformed
        if (bot3.isSelected()) {
            ProcessoDAO dao = new ProcessoDAO();
             
              DefaultTableModel dtm = (DefaultTableModel) tabelaProcessos.getModel();
                 dtm.setNumRows(0);
                 for (Processo pro : dao.pesquisarProcessoPorAcao(pesqTxt.getText())) {
            dtm.addRow(new Object[]{
                pro.getCod_processo(),
                pro.getAcao(),
                pro.getDescricao()});
                 }
        }else if (bot4.isSelected()) {
          ProcessoDAO dao = new ProcessoDAO();
             
              DefaultTableModel dtm = (DefaultTableModel) tabelaProcessos.getModel();
                 dtm.setNumRows(0);
                 for (Processo pro : dao.pesquisarProcessoPorDescricao(pesqTxt.getText())) {
            dtm.addRow(new Object[]{
                pro.getCod_processo(),
                pro.getAcao(),
                pro.getDescricao()});
                 }  
        }
    }//GEN-LAST:event_pesqTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acao;
    private javax.swing.JComboBox<Object> advo;
    private javax.swing.JTextField advogado;
    private javax.swing.JTextField bairro1;
    private javax.swing.JRadioButton bot1;
    private javax.swing.JRadioButton bot2;
    private javax.swing.JRadioButton bot3;
    private javax.swing.JRadioButton bot4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cep1;
    private javax.swing.JTextField cidade1;
    private javax.swing.JTextField cliente;
    private javax.swing.JComboBox<Object> clint;
    private javax.swing.JFormattedTextField cnpj1;
    private javax.swing.JTextField cod;
    private javax.swing.JTextField comple1;
    private javax.swing.JTextField ddd1;
    private javax.swing.JTextField descri;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField estado1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nome1;
    private javax.swing.JTextField nomef1;
    private javax.swing.JTextField num1;
    private javax.swing.JTextArea obs;
    private javax.swing.JComboBox<Object> pesqSele;
    private javax.swing.JTextField pesqTxt;
    private javax.swing.JButton pesquisar;
    private javax.swing.JTextField rua1;
    private javax.swing.JButton salv;
    private javax.swing.JTable tabelaProcessos;
    private javax.swing.JTextField tele1;
    // End of variables declaration//GEN-END:variables
}
