/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view.listas;

import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Advogado;
import model.bean.Cliente;
import model.bean.Email;
import model.bean.Endereco;
import model.bean.Oab;
import model.bean.Sexo;
import model.bean.Telefone;
import model.dao.AdvogadoDAO;
import model.dao.ClienteDAO;
import model.dao.EmailDAO;
import model.dao.EnderecoDAO;
import model.dao.OabDAO;
import model.dao.TelefoneDAO;
import model.view.TelaPricipal;
import model.view.cadastros.NovoEnderecoAdvogado;
import model.view.dados.DadosAdvogado;

/**
 *
 * @author Pedro
 */
public class ListarAdvogado extends javax.swing.JInternalFrame {
     JDesktopPane jDesktopPane1;
     TelaPricipal telinha;
     /**
     * Creates new form ListarPessoaFisica
     */
    public ListarAdvogado(TelaPricipal tel) {
        initComponents();
        this.telinha = tel;
            //
         
     pesq.setEditable(false);
//
      
       
        
    DefaultTableModel dtm = (DefaultTableModel) tabelaAdvogados.getModel();
        AdvogadoDAO aDAO = new AdvogadoDAO();
        for (Advogado adv : aDAO.listarAdvogado()) {
            dtm.addRow(new Object[]{
                adv.getCod_adv(),
                adv.getNome(),
                adv.getSobrenome(),
                adv.getCpf()});
        }
     
            
       
       
    }
    public ListarAdvogado( ) {
        initComponents();
        
            //
        
   
        
        
        
    DefaultTableModel dtm = (DefaultTableModel) tabelaAdvogados.getModel();
        AdvogadoDAO aDAO = new AdvogadoDAO();
        for (Advogado adv : aDAO.listarAdvogado()) {
            dtm.addRow(new Object[]{
                adv.getCod_adv(),
                adv.getNome(),
                adv.getSobrenome(),
                adv.getCpf()});
        }
     
            
       
       
    }
    ListarAdvogado(JDesktopPane jDesktopPane1) {
        initComponents();
        this.jDesktopPane1 = jDesktopPane1;
        DefaultTableModel dtm = (DefaultTableModel) tabelaAdvogados.getModel();
        AdvogadoDAO aDAO = new AdvogadoDAO();
        for (Advogado adv : aDAO.listarAdvogado()) {
            dtm.addRow(new Object[]{
              adv.getCod_adv(),
                adv.getNome(),
                adv.getSobrenome(),
                adv.getCpf()});
        }
        
       tabelaAdvogados.revalidate();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoes = new javax.swing.ButtonGroup();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAdvogados = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        sobre = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        rg = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        est = new javax.swing.JLabel();
        coab = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        tele = new javax.swing.JLabel();
        pesq = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();
        bot1 = new javax.swing.JRadioButton();
        bot2 = new javax.swing.JRadioButton();
        bot3 = new javax.swing.JRadioButton();
        bot4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setClosable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1120, 505));
        setRequestFocusEnabled(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabelaAdvogados.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tabelaAdvogados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Sobrenome", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAdvogados.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaAdvogados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAdvogadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaAdvogados);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Excluir");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Dados do Advogado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Informações Pessoais", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Sobrenome:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("CPF:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Data de Nascimento:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("RG:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Sexo:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Estado Civil:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Código OAB:");

        nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sobre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sobre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        data.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sexo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        est.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        est.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        coab.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        coab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coab, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addGap(360, 360, 360))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(est, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sobre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(est, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coab, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Informações Pessoais", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Email:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Telefone:");

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tele.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tele.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tele, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pesq.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pesq.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Pesquisar", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pesq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesqMouseClicked(evt);
            }
        });
        pesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqActionPerformed(evt);
            }
        });
        pesq.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pesqPropertyChange(evt);
            }
        });

        pesquisar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pesquisar.setText("Pesquisar");
        pesquisar.setBorder(null);
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        bot1.setBackground(new java.awt.Color(255, 255, 255));
        botoes.add(bot1);
        bot1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bot1.setText("Nome");
        bot1.setIconTextGap(1);
        bot1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot1MouseClicked(evt);
            }
        });
        bot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot1ActionPerformed(evt);
            }
        });

        bot2.setBackground(new java.awt.Color(255, 255, 255));
        botoes.add(bot2);
        bot2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bot2.setText("Sobrenome");
        bot2.setIconTextGap(2);
        bot2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot2MouseClicked(evt);
            }
        });
        bot2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bot2KeyPressed(evt);
            }
        });

        bot3.setBackground(new java.awt.Color(255, 255, 255));
        botoes.add(bot3);
        bot3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bot3.setText("Cidade");
        bot3.setIconTextGap(3);
        bot3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot3MouseClicked(evt);
            }
        });

        bot4.setBackground(new java.awt.Color(255, 255, 255));
        botoes.add(bot4);
        bot4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bot4.setText("Email");
        bot4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot4MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Pesquisar por:");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Mais Informações");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(pesq, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bot1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bot2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bot3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bot4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pesq)
                            .addComponent(pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bot1)
                            .addComponent(bot2)
                            .addComponent(bot3)
                            .addComponent(bot4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        AdvogadoDAO aDAO = new AdvogadoDAO();
        
        
        int linha = tabelaAdvogados.getSelectedRow();
        int codigoAdvogado = (int) tabelaAdvogados.getValueAt(linha, 0);
        if(aDAO.verificaExclusao(codigoAdvogado)){
            ListarProcesso proc = new ListarProcesso(this.telinha); 
            
            if (JOptionPane.showConfirmDialog(null, "O Advogado está envolvido em um processo, exclua o processo antes de excluir o advogado, deseja ir para processo?")==0) {
                
            
            
            telinha.jDesktopPane1.add(proc);
            proc.toFront();
            proc.show();
            } 
        }else{
            
        Advogado excluirAdv = new Advogado();
        excluirAdv.setCod_adv(codigoAdvogado);
        
        if (JOptionPane.showConfirmDialog(null, "Deseja excluir?") == 0) {
            aDAO.deletar(excluirAdv);
        }
        DefaultTableModel dtm = (DefaultTableModel) tabelaAdvogados.getModel();
        dtm.setNumRows(0);
        for (Advogado adv : aDAO.listarAdvogado()) {
            dtm.addRow(new Object[]{
                adv.getCod_adv(),
                adv.getNome(),
                adv.getSobrenome(),
                adv.getCpf()});
        }
        }
             
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelaAdvogadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAdvogadosMouseClicked
       //
        
       // 
        int linha = tabelaAdvogados.getSelectedRow();
        int codigoAdv = (int) tabelaAdvogados.getValueAt(linha, 0);
        String sexi=null;
        Sexo sex = new Sexo();
        Advogado adv = new Advogado();
        adv.setCod_adv(codigoAdv);
        AdvogadoDAO aDAO = new AdvogadoDAO();
        aDAO.buscarAdvogado(adv);
        
        if(adv.getSexo().getId()==1){
            sexi = "Masculino";
        }else{
            if(adv.getSexo().getId()==2){
                sexi = "Feminino";
            }else{
                
                }
        }    
       
        nome.setText(adv.getNome());
        sobre.setText(adv.getSobrenome());
        /////Data
        if(adv.getData_nasc()!=null){
        String datas[] = new String[3];    
        String datinha = String.valueOf(adv.getData_nasc());
        datas = datinha.split("-");
        data.setText(datas[2]+"/"+datas[1]+"/"+datas[0]);
        }else{
            data.setText("Vazio");
        }
        
       
        
       
        
       
        ///////////
        cpf.setText(adv.getCpf());
        rg.setText(adv.getRg());
        sexo.setText(sexi);
        est.setText(adv.getEst_civ());
        
       ///////Telefone 
       Telefone tel = new Telefone();
       TelefoneDAO tDAO = new TelefoneDAO();
       tel.setAdvogado(adv);
       tDAO.buscarTelefonePorAdvogado(tel);
        tele.setText("("+tel.getDdd()+")"+" "+tel.getNumero());
        /////////
       Email emi = new Email();
       EmailDAO emDAO = new EmailDAO();
       emi.setAdvogado(adv);
       emDAO.buscarEmailPorAdvogado(emi);
         email.setText(emi.getDescricao());
        /////////Código OAB/////////
         
        Oab oab = new Oab();
        oab.setCod_advogado(adv);
        OabDAO oDAO= new OabDAO();
        oDAO.buscarCodigoOabPorAdvogado(oab);
        coab.setText(oab.getCodigo());
        
       
      
        
      
       
    }//GEN-LAST:event_tabelaAdvogadosMouseClicked

    private void pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqActionPerformed
    if (bot1.isSelected()) {
              AdvogadoDAO dao = new AdvogadoDAO();
                DefaultTableModel dtm = (DefaultTableModel) tabelaAdvogados.getModel();
                 dtm.setNumRows(0);
                 for (Advogado adv : dao.pesquisarAdvogadoPorNome(pesq.getText())) {
            dtm.addRow(new Object[]{
                adv.getCod_adv(),
                adv.getNome(),
                adv.getSobrenome(),
                adv.getCpf()});
        }
        }else if(bot2.isSelected()){
          AdvogadoDAO dao = new AdvogadoDAO();
                DefaultTableModel dtm = (DefaultTableModel) tabelaAdvogados.getModel();
                 dtm.setNumRows(0);
                 for (Advogado adv : dao.pesquisarAdvogadoPorSobrenome(pesq.getText())) {
            dtm.addRow(new Object[]{
                adv.getCod_adv(),
                adv.getNome(),
                adv.getSobrenome(),
                adv.getCpf()});
        }
        }else if(bot3.isSelected()){
             AdvogadoDAO dao = new AdvogadoDAO();
                DefaultTableModel dtm = (DefaultTableModel) tabelaAdvogados.getModel();
                 dtm.setNumRows(0);
                 for (Advogado adv : dao.pesquisarAdvogadoPorCidade(pesq.getText())) {
            dtm.addRow(new Object[]{
                adv.getCod_adv(),
                adv.getNome(),
                adv.getSobrenome(),
                adv.getCpf()});
        }
        }else if(bot4.isSelected()){
            AdvogadoDAO dao = new AdvogadoDAO();
                DefaultTableModel dtm = (DefaultTableModel) tabelaAdvogados.getModel();
                 dtm.setNumRows(0);
                 for (Advogado adv : dao.pesquisarAdvogadoPorEmail(pesq.getText())) {
            dtm.addRow(new Object[]{
                adv.getCod_adv(),
                adv.getNome(),
                adv.getSobrenome(),
                adv.getCpf()});
        }
        }
    }//GEN-LAST:event_pesqActionPerformed

    private void pesqPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pesqPropertyChange
 
    }//GEN-LAST:event_pesqPropertyChange

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
           if (bot1.isSelected()) {
              AdvogadoDAO dao = new AdvogadoDAO();
                DefaultTableModel dtm = (DefaultTableModel) tabelaAdvogados.getModel();
                 dtm.setNumRows(0);
                 for (Advogado adv : dao.pesquisarAdvogadoPorNome(pesq.getText())) {
            dtm.addRow(new Object[]{
                adv.getCod_adv(),
                adv.getNome(),
                adv.getSobrenome(),
                adv.getCpf()});
        }
        }else if(bot2.isSelected()){
          AdvogadoDAO dao = new AdvogadoDAO();
                DefaultTableModel dtm = (DefaultTableModel) tabelaAdvogados.getModel();
                 dtm.setNumRows(0);
                 for (Advogado adv : dao.pesquisarAdvogadoPorSobrenome(pesq.getText())) {
            dtm.addRow(new Object[]{
                adv.getCod_adv(),
                adv.getNome(),
                adv.getSobrenome(),
                adv.getCpf()});
        }
        }else if(bot3.isSelected()){
            AdvogadoDAO dao = new AdvogadoDAO();
                DefaultTableModel dtm = (DefaultTableModel) tabelaAdvogados.getModel();
                 dtm.setNumRows(0);
                 for (Advogado adv : dao.pesquisarAdvogadoPorCidade(pesq.getText())) {
                dtm.addRow(new Object[]{
                adv.getCod_adv(),
                adv.getNome(),
                adv.getSobrenome(),
                adv.getCpf()});
        }
        }else if(bot4.isSelected()){
            AdvogadoDAO dao = new AdvogadoDAO();
                DefaultTableModel dtm = (DefaultTableModel) tabelaAdvogados.getModel();
                 dtm.setNumRows(0);
                 for (Advogado adv : dao.pesquisarAdvogadoPorEmail(pesq.getText())) {
            dtm.addRow(new Object[]{
                adv.getCod_adv(),
                adv.getNome(),
                adv.getSobrenome(),
                adv.getCpf()});
        }
        }
    }//GEN-LAST:event_pesquisarActionPerformed

    private void pesqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesqMouseClicked
     
    }//GEN-LAST:event_pesqMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
     
    }//GEN-LAST:event_formKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            /*
        TelaInicial tela = new TelaInicial();
        tela.setExtendedState(JFrame.MAXIMIZED_BOTH);
        tela.show();
        
        */
            int linha = tabelaAdvogados.getSelectedRow();
            int codigoAdv = (int) tabelaAdvogados.getValueAt(linha, 0);
            Advogado adv = new Advogado();
            adv.setCod_adv(codigoAdv);
            DadosAdvogado dAdvo = new DadosAdvogado(adv);
            dAdvo.setVisible(true);
            telinha.setExtendedState(JFrame.MAXIMIZED_BOTH);
            telinha.jDesktopPane1.add(dAdvo);
            dAdvo.toFront();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot1ActionPerformed
       
    }//GEN-LAST:event_bot1ActionPerformed

    private void bot1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot1MouseClicked
       pesq.setEditable(true);
    }//GEN-LAST:event_bot1MouseClicked

    private void bot2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bot2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bot2KeyPressed

    private void bot2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot2MouseClicked
      pesq.setEditable(true);
    }//GEN-LAST:event_bot2MouseClicked

    private void bot3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot3MouseClicked
       pesq.setEditable(true);
    }//GEN-LAST:event_bot3MouseClicked

    private void bot4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot4MouseClicked
         pesq.setEditable(true);
    }//GEN-LAST:event_bot4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bot1;
    private javax.swing.JRadioButton bot2;
    private javax.swing.JRadioButton bot3;
    private javax.swing.JRadioButton bot4;
    private javax.swing.ButtonGroup botoes;
    private javax.swing.JLabel coab;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel data;
    private javax.swing.JLabel email;
    private javax.swing.JLabel est;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nome;
    private javax.swing.JTextField pesq;
    private javax.swing.JButton pesquisar;
    private javax.swing.JLabel rg;
    private javax.swing.JLabel sexo;
    private javax.swing.JLabel sobre;
    private javax.swing.JTable tabelaAdvogados;
    private javax.swing.JLabel tele;
    // End of variables declaration//GEN-END:variables
}
